# Likes Report

## Section 1 - Questions about data

### James Pauline, 9/10/2025

#### I am the source of the analyzed instagram data, as the likes being analyzed are my own

#### This data was created to track what posts ive liked and it serves the purpose of guaging what content I am interested in

#### This data would be reliable because it was generated by the Meta company

#### This data could also be somewhat unreliable due to my inconsistent use of the instagram platform

## Section 2 - Open and load the json file

In [1]:
# import statements
import json 
import pandas as pd
import matplotlib as plt

In [2]:
path = r"C:\Users\jttor\Downloads\instagram-jam.t.p-2025-08-25-eDfHKeoA\your_instagram_activity\likes\liked_posts.json"
with open (path) as l:
    dict = json.load(l)

## Section 3 - Convert the data into DataFrame object and assign it to a variable using pandas

In [3]:
df = pd.DataFrame(dict)
df.head()

                                   likes_media_likes
0  {'title': 'marcuspork', 'string_list_data': [{...
1  {'title': 'yung_dawnn', 'string_list_data': [{...
2  {'title': 'jocelynmarcucci', 'string_list_data...
3  {'title': 'misspaige.elizabeth', 'string_list_...
4  {'title': 'paigethrowsclay', 'string_list_data...

In [4]:
# find keys
dict.keys()

dict_keys(['likes_media_likes'])

In [5]:
df_tidy = pd.DataFrame(dict['likes_media_likes'])
df_tidy.head()

                 title                                   string_list_data
0           marcuspork  [{'href': 'https://www.instagram.com/reel/DMQf...
1           yung_dawnn  [{'href': 'https://www.instagram.com/reel/DKiB...
2      jocelynmarcucci  [{'href': 'https://www.instagram.com/p/DLwFT9M...
3  misspaige.elizabeth  [{'href': 'https://www.instagram.com/p/DLgLVm7...
4      paigethrowsclay  [{'href': 'https://www.instagram.com/p/DLnxfDa...

## Section 4 - create a timestamp column

In [6]:
df_tidy['string_list_data'].iloc[0]

[{'href': 'https://www.instagram.com/reel/DMQfOc-pcnQ/',
  'value': 'รฐ\x9f\x91\x8d',
  'timestamp': 1752938141}]

In [7]:
type(df_tidy['string_list_data'].iloc[0])

list

In [8]:
len(df_tidy['string_list_data'].iloc[0])

1

In [9]:
df_tidy['string_list_data'].iloc[0][0]

{'href': 'https://www.instagram.com/reel/DMQfOc-pcnQ/',
 'value': 'รฐ\x9f\x91\x8d',
 'timestamp': 1752938141}

In [10]:
df_tidy['string_list_data'].iloc[0][0]['timestamp']

1752938141

In [11]:
df_tidy['Time of Like'] = [i[0]['timestamp'] for i in df_tidy['string_list_data']]

df_tidy.head()

,title,string_list_data,Time of Like
0,marcuspork,[{'href': 'https://www.instagram.com/reel/DMQf...,1752938141
1,yung_dawnn,[{'href': 'https://www.instagram.com/reel/DKiB...,1752335042
2,jocelynmarcucci,[{'href': 'https://www.instagram.com/p/DLwFT9M...,1751780620
3,misspaige.elizabeth,[{'href': 'https://www.instagram.com/p/DLgLVm7...,1751780378
4,paigethrowsclay,[{'href': 'https://www.instagram.com/p/DLnxfDa...,1751778378

In [12]:
# good to have
from datetime import datetime
df_tidy['Date of Like'] = [datetime.fromtimestamp(i[0]['timestamp']) for i in df_tidy['string_list_data']]

In [13]:
df_tidy.head()

,title,string_list_data,Time of Like,Date of Like
0,marcuspork,[{'href': 'https://www.instagram.com/reel/DMQf...,1752938141,2025-07-19 11:15:41
1,yung_dawnn,[{'href': 'https://www.instagram.com/reel/DKiB...,1752335042,2025-07-12 11:44:02
2,jocelynmarcucci,[{'href': 'https://www.instagram.com/p/DLwFT9M...,1751780620,2025-07-06 01:43:40
3,misspaige.elizabeth,[{'href': 'https://www.instagram.com/p/DLgLVm7...,1751780378,2025-07-06 01:39:38
4,paigethrowsclay,[{'href': 'https://www.instagram.com/p/DLnxfDa...,1751778378,2025-07-06 01:06:18

In [14]:
df_tidy['href'] = [i[0]['href'] for i in df_tidy['string_list_data']]
df_tidy.head()

,title,string_list_data,Time of Like,Date of Like,href
0,marcuspork,[{'href': 'https://www.instagram.com/reel/DMQf...,1752938141,2025-07-19 11:15:41,https://www.instagram.com/reel/DMQfOc-pcnQ/
1,yung_dawnn,[{'href': 'https://www.instagram.com/reel/DKiB...,1752335042,2025-07-12 11:44:02,https://www.instagram.com/reel/DKiBTJVu8d2/
2,jocelynmarcucci,[{'href': 'https://www.instagram.com/p/DLwFT9M...,1751780620,2025-07-06 01:43:40,https://www.instagram.com/p/DLwFT9MMYkc/
3,misspaige.elizabeth,[{'href': 'https://www.instagram.com/p/DLgLVm7...,1751780378,2025-07-06 01:39:38,https://www.instagram.com/p/DLgLVm7OPrf/
4,paigethrowsclay,[{'href': 'https://www.instagram.com/p/DLnxfDa...,1751778378,2025-07-06 01:06:18,https://www.instagram.com/p/DLnxfDaAsIY/

In [15]:
df_tidy['value'] = [i[0]['value'] for i in df_tidy['string_list_data']]
df_tidy.head()

,title,string_list_data,Time of Like,Date of Like,href,value
0,marcuspork,[{'href': 'https://www.instagram.com/reel/DMQf...,1752938141,2025-07-19 11:15:41,https://www.instagram.com/reel/DMQfOc-pcnQ/,รฐยยย
1,yung_dawnn,[{'href': 'https://www.instagram.com/reel/DKiB...,1752335042,2025-07-12 11:44:02,https://www.instagram.com/reel/DKiBTJVu8d2/,รฐยยย
2,jocelynmarcucci,[{'href': 'https://www.instagram.com/p/DLwFT9M...,1751780620,2025-07-06 01:43:40,https://www.instagram.com/p/DLwFT9MMYkc/,รฐยยย
3,misspaige.elizabeth,[{'href': 'https://www.instagram.com/p/DLgLVm7...,1751780378,2025-07-06 01:39:38,https://www.instagram.com/p/DLgLVm7OPrf/,รฐยยย
4,paigethrowsclay,[{'href': 'https://www.instagram.com/p/DLnxfDa...,1751778378,2025-07-06 01:06:18,https://www.instagram.com/p/DLnxfDaAsIY/,รฐยยย

In [16]:
df_tidy.drop(columns = ['string_list_data'])

,title,Time of Like,Date of Like,href,value
0,marcuspork,1752938141,2025-07-19 11:15:41,https://www.instagram.com/reel/DMQfOc-pcnQ/,รฐยยย
1,yung_dawnn,1752335042,2025-07-12 11:44:02,https://www.instagram.com/reel/DKiBTJVu8d2/,รฐยยย
2,jocelynmarcucci,1751780620,2025-07-06 01:43:40,https://www.instagram.com/p/DLwFT9MMYkc/,รฐยยย
3,misspaige.elizabeth,1751780378,2025-07-06 01:39:38,https://www.instagram.com/p/DLgLVm7OPrf/,รฐยยย
4,paigethrowsclay,1751778378,2025-07-06 01:06:18,https://www.instagram.com/p/DLnxfDaAsIY/,รฐยยย
...,...,...,...,...,...
144,j7krazy,1726193645,2024-09-12 22:14:05,https://www.instagram.com/reel/C7Wkm5esYyr/,รฐยยย
145,rosieinthesunshine,1726005132,2024-09-10 17:52:12,https://www.instagram.com/reel/C_wE5YXP5bi/,รฐยยย
146,rosieinthesunshine,1726003562,2024-09-10 17:26:02,https://www.instagram.com/reel/C_wElzBPXGH/,รฐยยย
147,shake_1121,1725697211,2024-09-07 04:20:11,https://www.instagram.com/reel/C_VPPodpZup/,รฐยยย
148,rosieinthesunshine,1725050577,2024-08-30 16:42:57,https://www.instagram.com/reel/C_Trfcyv1OP/,รฐยยย

## Section 5 - use groupby() and count() mathods

In [17]:
df_tidy.groupby('title').count().sort_values('Time of Like', ascending = False)

                     string_list_data  Time of Like  Date of Like  href  value
title
rosieinthesunshine                 18            18            18    18     18
igndotcom                           4             4             4     4      4
epaul5305                           3             3             3     3      3
bipolarerpolarfisch                 2             2             2     2      2
tabbycatmittens                     2             2             2     2      2
...                               ...           ...           ...   ...    ...
doggvids                            1             1             1     1      1
diorgasms                           1             1             1     1      1
digital.chomeur                     1             1             1     1      1
dexerto                             1             1             1     1      1
zaddysscarystories                  1             1             1     1      1

[120 rows x 5 columns]

## Section 6 - Create a hypothesis that could be proved or disproved using another personal json file

I have followed more friend related accounts than other accounts recently (Content creators, companies, meme pages, etc)

## Section 7 - Chose json file I think may be applicable

I have selected the file named following.json. Ideally this file will give me a good idea about how many real-life friends I follow on instagram by analyzing the first several entries

## Section 8 - Open and load following.json

In [18]:
path = r"C:\Users\jttor\Downloads\instagram-jam.t.p-2025-08-25-eDfHKeoA\connections\followers_and_following\following.json"
with open (path) as follow:
    dict = json.load(follow)

## Section 9 - Convert the data to as tidy of a form as possible

In [19]:
df = pd.DataFrame(dict)
df.head

<bound method NDFrame.head of                               relationships_following
0   {'title': '', 'media_list_data': [], 'string_l...
1   {'title': '', 'media_list_data': [], 'string_l...
2   {'title': '', 'media_list_data': [], 'string_l...
3   {'title': '', 'media_list_data': [], 'string_l...
4   {'title': '', 'media_list_data': [], 'string_l...
5   {'title': '', 'media_list_data': [], 'string_l...
6   {'title': '', 'media_list_data': [], 'string_l...
7   {'title': '', 'media_list_data': [], 'string_l...
8   {'title': '', 'media_list_data': [], 'string_l...
9   {'title': '', 'media_list_data': [], 'string_l...
10  {'title': '', 'media_list_data': [], 'string_l...
11  {'title': '', 'media_list_data': [], 'string_l...>

In [20]:
dict.keys()

dict_keys(['relationships_following'])

In [21]:
df_tidy = pd.DataFrame(dict['relationships_following'])

In [22]:
df_tidy.head()

  title media_list_data                                   string_list_data
0                    []  [{'href': 'https://www.instagram.com/lexiscali...
1                    []  [{'href': 'https://www.instagram.com/sarahhope...
2                    []  [{'href': 'https://www.instagram.com/paigethro...
3                    []  [{'href': 'https://www.instagram.com/misspaige...
4                    []  [{'href': 'https://www.instagram.com/delaneypa...

In [23]:
df_tidy['Account'] = [i[0]['value'] for i in df_tidy['string_list_data']]

df_tidy.head()

,title,media_list_data,string_list_data,Account
0,,[],[{'href': 'https://www.instagram.com/lexiscali...,lexiscalise
1,,[],[{'href': 'https://www.instagram.com/sarahhope...,sarahhopebeck
2,,[],[{'href': 'https://www.instagram.com/paigethro...,paigethrowsclay
3,,[],[{'href': 'https://www.instagram.com/misspaige...,misspaige.elizabeth
4,,[],[{'href': 'https://www.instagram.com/delaneypa...,delaneyparisi

In [24]:
df_tidy.drop(columns = ['string_list_data'])
df_tidy.drop(columns = ['media_list_data'])

,title,string_list_data,Account
0,,[{'href': 'https://www.instagram.com/lexiscali...,lexiscalise
1,,[{'href': 'https://www.instagram.com/sarahhope...,sarahhopebeck
2,,[{'href': 'https://www.instagram.com/paigethro...,paigethrowsclay
3,,[{'href': 'https://www.instagram.com/misspaige...,misspaige.elizabeth
4,,[{'href': 'https://www.instagram.com/delaneypa...,delaneyparisi
5,,[{'href': 'https://www.instagram.com/jocelynma...,jocelynmarple
6,,[{'href': 'https://www.instagram.com/julesonbr...,julesonbrand
7,,[{'href': 'https://www.instagram.com/l.mitchhh...,l.mitchhhhh
8,,[{'href': 'https://www.instagram.com/mike.wags...,mike.wags28
9,,"[{'href': 'https://www.instagram.com/iam_412',...",iam_412
10,,[{'href': 'https://www.instagram.com/usebothof...,usebothofyoureyes_daily
11,,[{'href': 'https://www.instagram.com/epaul5305...,epaul5305

## Section 10 - In a Markdown cell, describe what you think the data in the DataFrame represents, whether the DataFrame meets tidy principles, and whether the data can be used to test your hypothesis.

The data in the DataFrame represents the accounts that I follow in the far right column. I do believe this meets tidy principles, as unnecessary columns have been removed. This data could easily be used to test my hypothesis.

By looking at the account names, I can tell that 10 of the 12 listed accounts are people that I personally know, confirming my hypothesis.